router.get('/version/', connections.getVersion); 
router.get('/users/:login/:haslo/:hash', connections.getUser);
router.get('/all_users/:token', verifyToken, connections.getAllUsers);
router.get('/lista-userow', connections.getUsersM);
router.get('/islogged/:token', verifyToken, connections.isLogged);
router.get('/zamowienia_proofy/:token', verifyToken, connections.getZamowieniaProofy);
router.get('/zamowieniapliki/:token', verifyToken, connections.getZamowieniaPliki);
router.get('/zamowieniaKalendarz/:token', verifyToken, connections.getZamowieniaKalendarz);
router.get('/oddania_grupy/:widok/:token', verifyToken, connections.getOddaniaGrupy);
router.get('/oddania_wykonania/:grupa_global_id/:token', verifyToken, connections.getOddaniaWykonania);
router.get('/technologie_parametry/:idTechnologii/:token', verifyToken, connections.getParametryTechnologii);
router.get('/gantGrupy/:token', verifyToken, connections.getGantGrupy);
router.get('/technologie/:token', verifyToken, connections.getTechnologie);
router.get('/papiery-parametry/:token', verifyToken, connections.getPapieryParametry);
router.get('/sprawdzCzyPapierUzyty/:papier_id/:token', verifyToken, connections.sprawdzCzyPapierUzyty);
router.get('/lista-papierow/:token', verifyToken, connections.getListaPapierow);
router.get('/lista-papierow-nazwy/:token', verifyToken, connections.getListaPapierowNazwy);
router.get('/lista-papierow-grupa/:token', verifyToken, connections.getListaPapierowGrupa);
router.get('/lista-papierow-postac/:token', verifyToken, connections.getListaPapierowPostac);
router.get('/lista-papierow-rodzaj/:token', verifyToken, connections.getListaPapierowRodzaj);
router.get('/lista-papierow-wykonczenia/:token', verifyToken, connections.getListaPapierowWykonczenia);
router.get('/lista-papierow-powleczenie/:token', verifyToken, connections.getListaPapierowPowleczenie);
router.put('/updatePaper/:token', verifyTokenParams('papier_zapis'), connections.updatePapiery);
router.put('/updatePaperNazwy/:token', verifyTokenParams('papier_zapis'), connections.updatePapieryNazwy);
router.put('/updatePaperGrupa/:token', verifyTokenParams('papier_zapis'), connections.updatePapieryGrupa);
router.get('/nadkomplety/:token', verifyToken, connections.getNadkomplety);
router.get('/podglad_realizacji_dzien/:dniWstecz/:token', verifyToken, connections.getPodgladRealizacji);
router.put('/updateHistoria/:token', verifyToken, connections.updateHistoria);
router.put('/updateWydaniePapieru_status/:token', verifyToken, connections.updateWydaniePapieru_status);
router.post('/insertWydaniePapieru_status/:token', verifyToken, connections.insertWydaniePapieru_status);
router.post('/insertWydaniePapieru_status_multiselect/:token', verifyToken, connections.insertWydaniePapieru_status_multiselect);
router.put('/zmien_status_przerwy/:token', verifyToken, connections.zmien_status_przerwy);
router.put('/zamowienia_not_final', connections.updateSetOrderNotFinal);
router.put('/delete_zamowienie_kosz', connections.updateSetOrderToDeleted);
router.get('/lista-procesow', connections.getListaProcesow);
router.get('/lista-procesow-nazwa', connections.getListaProcesowNazwa);
router.get('/procesyElementow', connections.getProcesyElementow);
router.get('/procesory', connections.getProcesory);
router.get('/lista-produktow', connections.getProdukty);
router.put('/setOrderOpen', connections.setOrderOpen);
router.put('/setOrderClosed', connections.setOrderClosed);
router.get('/technologie_grupyWykonan/:token', verifyToken, connections.getGrupyAll);
router.get('/technologie_grupy_an_wykonania_for_procesor_dni_wstecz_oprawa/:procesor_id/:dniWstecz', connections.getWykonania_i_grupy_for_procesor_dni_wstecz_oprawa);
router.get('/technologie_grupy_oprawa_for_procesor/:procesor_id', connections.getGrupy_oprawa_for_procesor);
router.get('/drag_drop_proces_grupa/:id_drag_grupa_proces/:id_drop_grupa_proces', connections.dragDropProcesGrup);
router.put('/drag_drop_proces_grupa_multi/:token', verifyToken, connections.dragDropProcesGrupMulti);
router.get('/drag_drop_proces_grupa_oprawa/:id_drag_grupa_proces/:id_drop_grupa_proces', connections.dragDropProcesGrupOprawa);
router.get('/drag_drop_proces_grupa_to_procesor/:id_drag_grupa_proces/:id', connections.dragDropProcesGrupToProcesor);
router.get('/updateWykonania/:global_id_wykonania/:kolumna/:wartosc', connections.updateWykonania);
router.get('/updateWydzielWykonanieZgrupy/:global_id_wykonania', connections.updateWydzielWykonanieZgrupy);
router.get('/updatePrzeniesWykonanieDoInnejGrupy/:global_id_wykonania/:grupa_id_drop/:ostatnie_wykonania', connections.updatePrzeniesWykonanieDoInnejGrupy);
router.get('/updateAddPrzerwa/:global_id_grupa/:czas', connections.updateAddPrzerwa);
router.get('/updateAddPrzerwaOprawa/:global_id_grupa/:czas', connections.updateAddPrzerwaOprawa);
router.get('/updateAddPrzerwaMagic/:global_id_grupa/:czas', connections.updateAddPrzerwaMagic);
router.get('/updateDeletePrzerwa/:global_id_grupa', connections.updateDeletePrzerwa);
router.get('/updateDeletePrzerwaOprawa/:global_id_grupa', connections.updateDeletePrzerwaOprawa);
router.get('/zmienCzasTrwaniaGrupy/:drop_grupa_global_id/:nowy_koniec', connections.zmienCzasTrwaniaGrupy);
router.get('/zmienCzasTrwaniaGrupyOprawa/:drop_grupa_global_id/:nowy_koniec', connections.zmienCzasTrwaniaGrupyOprawa);
router.get('/zmienCzasTrwaniaGrupyOprawaPrzerwa/:drop_grupa_global_id/:nowy_koniec', connections.zmienCzasTrwaniaGrupyOprawaPrzerwa);
router.get('/zmienCzasTrwaniaGrupyPrzerwa/:drop_grupa_global_id/:nowy_koniec', connections.zmienCzasTrwaniaGrupyPrzerwa);
router.get('/skasujGrupe/:global_id_grupa/:token', verifyTokenParams('technologia_zapis'), connections.skasujGrupe);
router.get('/skasujGrupeOprawa/:global_id_grupa/:token', verifyTokenParams('technologia_zapis'), connections.skasujGrupeOprawa);
router.get('/skasujTechnologie/:id_delete/:zamowienie_id/:user_id/:token', verifyTokenParams('technologia_zapis'), connections.skasujTechnologie);
router.delete('/delete_zamowienie/:token', verifyTokenParams('zamowienie_skasuj'), connections.deleteZamowienie);
router.delete('/odblokuj_zamowienie/:token', verifyToken, connections.odblokujZamowienie);
router.get('/backup/:token', verifyTokenParams('technologia_zapis'), connections.backup);
router.get('/pool/:token', verifyTokenParams('technologia_zapis'), connections.sprawdzPulePolaczen);
router.post('/klienci/:token', verifyTokenParams('klienci_zapis'), connections.postKlient);
router.put('/klient/:token', verifyTokenParams('klienci_usun'), connections.deleteKlient);
router.put('/updateKlient/:token', verifyTokenParams('klienci_zapis'), connections.updateKlient);